data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: ./configs/dataset/train.yaml
    # Path to validation set configuration file.
    val_config: ./configs/dataset/val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/pixel_prior.yaml
  # Path to the checkpoints or weights you want to resume.
  resume: ./weights/general_swinir_v1.ckpt

lightning:
  seed: 231
  
  trainer:
    accelerator: ddp
    precision: 32
    # Indices of GPUs used for training.
    gpus: [0]
    # Path to save logs and checkpoints.
    default_root_dir: ./weights/NUAA_stage1/
    # Max number of training steps (batches).
    max_steps: 20000
    # Validation frequency in terms of training steps.
    val_check_interval: 40
    # Log frequency of tensorboard logger.
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 100
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 500
        save_top_k: -1
        filename: "{step}"
